### ISSUE TITLE
#363 tracking and cleanup

### ISSUE THREAD

**Issue by rpkilby** [philipn/django-rest-framework-filters#62]
The following issues should be merged once carltongibson/django-filter#363 is merged/released.

The above PR fixes longstanding issues with filter generation for various lookup types ('isnull', 'in', 'range'), as well as the newly introduced lookup transforms.

- #2
- #15
- #16

TODO:
- [x] finish 363
- [x] wait for next release
- [x] remove `fix_field_filter`, as it should no longer be necessary
- [x] deprecate `InSetNumberFilter`/`InSetCharFilter`
- [x] fix AllLookupsFilter handling
